### ISSUE TITLE
Suggestion: ability to launch programs from the LG Controller scripts

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#101]
The 'Add step' option allows you to add buttons, actions and Nvidia presets. It would be great if you could add .exe files as well.

For example, I wrote 2 small scripts in order to enable/disable my GPU in the device manager. The reason I've done this is because if I power off the TV from ColorControl and I power on later I lose the Gsync logo when I check it in the Game Optimizer menu on my LG. However I've found that if I disable and enable the GPU in the Windows device manager (or if I restart Windows) the logo appears again. That's what my small EXEs do: one disables the GPU and the other one enables it again. So far I have to manually launch them but I think this process could be automatized if ColorControl lets you add these files as a new kind of step. I think this feature would also be useful in other scripts. What do you think?

**Comment by Maassoft** [comment]
Yes, I think this will be useful. I think I can add this in the release that comes after the upcoming release.
The next release will maybe help you out a bit as well, because I've found a way to change the driver settings of Nvidia (thanks to source code of Nvidia Profile Inspector). With that I can toggle all driver settings including whether G-SYNC is enabled or not. So maybe that might help. I'll have to integrate it first in ColorControl and it may take a while if any issues come along.

**Comment by javsp** [comment]
Unfortunately disabling/enabling G-Sync from Nvidia ontrol Panel doesn't force the G-Sync logo to show again. I think this only happens when the TV recognnizes a G-Sync compatible GPU for the first time in a session. This only occurs when Windows is starting or when I manually restart the GPU from the device manager.

But yeah, having access to the Nvidia driver settings would also be useful for other purposes.

**Comment by javsp** [comment]
> Added to LG controller:
>
> - in the steps you can now also add programs that should be executed (Add step->Start Program)

Thank you for adding this feature in the latest version. It works great.
