### ISSUE TITLE
Newest version does not keep profile active on restart with below error

### ISSUE THREAD

**Issue by Harry83** [Maassoft/ColorControl#11]
2021-01-16 15:49:46.5421|ERROR|ColorControl.GraphicsService|Could not set dithering because NvAPI_Disp_SetDitherControl returned a non-zero return code: 4294967192

**Comment by Harry83** [comment]
This is with latest Nvidia driver on LG OLED C9

**Comment by Maassoft** [comment]
The application does not automatically activate a profile on startup. Do you manually apply a Nvidia preset which causes this error? If so, could you check if both the Bit depth and Mode have an item with a check mark in front of it? Like this:
![image](https://user-images.githubusercontent.com/70057942/104819764-fa3de680-582f-11eb-838a-64e0c15649e0.png)

**Comment by Harry83** [comment]
![Capture](https://user-images.githubusercontent.com/45322107/104821741-e1383400-5835-11eb-971d-d5afad17dd41.JPG)
This is with a custom profile. But I can confirm they are ticked as your example shows. I'm not sure exactly at what point the error is created. I will keep trying to re-create it.

Is there a way to have this apply that profile on start-up so 6bit is always applied?

**Comment by Harry83** [comment]
Also is there a reason why the active profile doesn't highlight like the first line - was a bit confusing as I though the profile would not load.
It's a great app by the way, I like the LG control - nice touch! Appreciate your work on this.

**Comment by Harry83** [comment]
OK, I reliably re-created the error. Happens when re-starting the computer and opening the application, for first few seconds, there is no error in the log, then after looking in options tab and going back to log, error is there.

I changed the profile based on what we spoke about on AVS. 

Like this there is almost no banding in PC mode or console mode but as previously mentioned, every time windows starts up, it's back to 8bit and you can tell by some slight banding visible on your greyscale ramp. When I choose my custom profile, the ramp is clean again and showing 6bit by default.
![Capture](https://user-images.githubusercontent.com/45322107/104822686-4727ba00-583c-11eb-9aea-96bdf2f8b204.JPG)

**Comment by Maassoft** [comment]
Thanks for investigating this. There's a known issue that the application can't read the active dithering bit depth/mode at this time. The Nvidia API for changing/reading dithering settings is undocumented and so far I can only apply dithering settings and not read back the actual settings. That's why the Dithering column in the active preset row is empty. And that's also why the app reverts to 8-bit as soon as you open the Options tab when there's no normal preset selected. I think it's at 6-bit on your system as well after startup, but if you select the Options tab it defaults to 8-bit.
I think I will add an option to apply a preset on startup, that way the app knows what settings were used.

**Comment by Harry83** [comment]
Cool, that sounds like a decent way to work around it. Hopefully you can find a way to read the settings..

Let me know if you want me to test anything.

**Comment by Maassoft** [comment]
I've created a new release with the option to apply a preset on startup. Feel free to test it.
