### ISSUE TITLE
repeating error

### ISSUE THREAD

**Issue by fingerpad** [Maassoft/ColorControl#167]
hi. this error window shows up when i run ColorControl and reappears whenever i click OK. i can prevent the error from returning with some weird trick, but the Log tab is empty. at this point if i switch window focus then the error reappears.

i'm using the windows service elevation method on windows 10, and i had an amd graphics card several years ago but not anymore, if that has anything to do with the error.

![image](https://user-images.githubusercontent.com/48131189/212532602-241bd4c6-d1c5-42ef-bd4b-839e78878fe2.png)

**Comment by Maassoft** [comment]
This error popping up could have something to do with you having an AMD card earlier. The AMD controller tab page is visible in your case? Maybe some remnants from the AMD graphics driver are still on your system and ColorControl erroneously activated the AMD functionality. If the driver is old that immediately explains why the HDR function is not supported.
Can you go into the Windows settings and check under "Installed apps" if there is still AMD software installed (for GPU's)?
Meanwhile I can try to make the code a bit more robust (error logging instead of popups).

**Comment by fingerpad** [comment]
the AMD tab was not visible for me. the Nvidia tab showed up as it should. there was no trace of AMD or ATI software in Installed Apps.

i used Display Driver Uninstaller to clean out the remnants of any AMD drivers on my PC and that seems to have fixed the problem. no more errors. i probably should have cleaned up the remnants a long time ago!
