### ISSUE TITLE
Repeated remote control clicks don't always get triggered

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#17]
Steps to reproduce:
- add a new shortcut with these steps: "RIGHT:500, ENTER:1000, DOWN, ENTER, ENTER, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, LEFT, EXIT"
- set the brightness to the maximum
- apply the script 5 times

Expected:
- the brightness decreases to 80 then 60, 40, 20, and finally 0

Actual:
- the brightness decreases to 81, 61, 42, 22, 3 unreliably

**Comment by Maassoft** [comment]
This might be caused by the default delay between clicks which is too low. If you don't specify a delay (the 500 part after RIGHT means 500ms delay), a delay of 180ms is used. I do not have an issue with this on my C9, but if I lower it to about 120ms I get the same problem. You could try adding :250 to each LEFT click so there's about 70ms extra delay per click.
If that works, I can add a setting under Options where you can change the default delay.

**Comment by MahmoudAlyuDeen** [comment]
I tried adding a delay to each LEFT and RIGHT but it didn't solve the problem for me, I'm using CX and both the TV and PC are on WiFi, so maybe it also has to do with network connectivity/lags/network quality.

What did work for me reliably is adding a bigger delay to the last ENTER and the last LEFT/RIGHT:

```
RIGHT:500, ENTER:1000, DOWN, ENTER, ENTER:500, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:250, LEFT:500, EXIT

RIGHT:500, ENTER:1000, DOWN, ENTER, ENTER:500, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:250, RIGHT:500, EXIT
```

That gives me perfect 0,20,40,60,80,100 and also lets me see the final number before closing the menu.

Thanks a lot for the assistance!
