### ISSUE TITLE
Feature Request: sRGB clamp?

### ISSUE THREAD

**Issue by AeliusSaionji** [Maassoft/ColorControl#222]
Would implementing nvidia's sRGB clamp be within the scope of colorcontrol? It would be nice to include this function as part of colorcontrol profiles.

https://github.com/ledoge/novideo_srgb

**Comment by DitherMan420** [comment]
I agree. It would be wonderful to have this built into the app so that I do not have to use 2 apps. Novideo_srgb actually has dithering as well, lol.

**Comment by Maassoft** [comment]
Thanks for the suggestion.
Integrating this is possible, but I don't know how whether the creator of Novideo sRGB will appreciate this. Also updates to this app would require me to update CC as well. Another option would be command line support of this app so you can start it from CC presets.

**Comment by DitherMan420** [comment]
> Thanks for the suggestion. Integrating this is possible, but I don't know how whether the creator of Novideo sRGB will appreciate this. Also updates to this app would require me to update CC as well. Another option would be command line support of this app so you can start it from CC presets.

I think novideo_srgb is abandoned. The author said on reddit he's not updating it anymore. I don't think it would bother him? I mean novideo_srgb also has dithering controls. Does that bother you? I doubt it. I guess I'm just not seeing the problem here? All these apps are doing is accessing the nvidia API. It's not anyone created dithering on nvidia GPUs. All it's doing is accessing the API. Let me know if I am thinking about this incorrectly.

**Comment by Maassoft** [comment]
New feature of Visual Studio/GitHub seems to automatically close issues if I mention it in the commit details.
Anyway, v9.5.0.0 now contains the Novideo sRGB clamp.

**Comment by DitherMan420** [comment]
> New feature of Visual Studio/GitHub seems to automatically close issues if I mention it in the commit details. Anyway, v9.5.0.0 now contains the Novideo sRGB clamp.

You sir are a hero. Yea the srgb clamp is super helpful in SDR mode!
