### ISSUE TITLE
[feature request] Switch input mode instantly

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#30]
Hi, I just tried the last version and I can see that all the settings under the new "expert" button are being applied instantly without manually navigating through settings menus, AMAZING WORK! I can confirm that it works like a charm on my CX.

I was wondering if the same can be done to switch the HDMI input from HDMI to PC and vice versa, usually done from the HomeDashboard app -> edit -> HDMI icon

Thanks for all the great work you're doing to make LG OLED owners lives easier ❤️

**Comment by Maassoft** [comment]
Thanks!
I've looked into this and there seem to be hidden inputs like HDMI1_PC, HDMI2_PC, etc, beside the "normal" inputs HDMI1, HDMI2 and so forth. I've tried to change the input on my tv to one of these and back again but there was no change at all. Maybe they belonged to older versions where you could only label a HDMI connection as PC or not and you did not have a list of labels like in the Home Dashboard now. I'll try to see if I can find something...
BTW, I currently only have some of the "source" code of the front-end of the Settings app, which is a lot of de-minimized javascript code. This gave me a lot of insight. But I don't have the source code of the Dashboard app so that's making it more difficult.
