### ISSUE TITLE
ETA for LG controller support for 2024 G4/C4

### ISSUE THREAD

**Issue by jerrytsao1985** [Maassoft/ColorControl#351]
Just connected to a G4, the message shows "It seems no LG TV available! Please make sure it's connected to the same network as this PC", when can we expect support for the latest series?

**Comment by Maassoft** [comment]
Auto-detection relies on Windows' auto-discovery of devices and it could be that it hasn't discovered it yet, especially after just connecting. You can check in Device Manager under Software devices if the LG G4 is listed there.
Otherwise, you can always add the TV manually by specifying the IP address and MAC address (optionally).
If you know the IP address you can verify if the LG webservices are running by entering this in a browser:

`https://ip-address:3000`

Unless LG changed something drastically this year it should work.

**Comment by jerrytsao1985** [comment]
Thanks for the quick replay, The TV now is able to be connected automatically to the software, however I couldn't find the "Enable Full Service Menu" toggle under expert, is this normal?

**Comment by Maassoft** [comment]
Yes, support for enabling the full service menu for 2024 models will be added in the next version.

**Comment by jerrytsao1985** [comment]
Thank you for your amazing work
