### ISSUE TITLE
You must install .NET desktop runtime to run this application

### ISSUE THREAD

**Issue by nommy125** [Maassoft/ColorControl#402]
![image](https://github.com/user-attachments/assets/ebdef04c-4277-4259-b9a8-682765de4d7a)

All Desktop Runtimes 6.7,8 are installed, Latest version Desktop runtime 8.08. Still get this message. Download it now link does not work either.

**Comment by YuGhi-bug** [comment]
same problem

**Comment by pumpknman** [comment]
https://github.com/Maassoft/ColorControl/issues/393

**Comment by SyCoREAPER** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

You need x86 and x64 installed.

**Comment by Amoeba00** [comment]
I think the issue is with Win 10 folks and/or maybe older Win 11 builds.  There was a [post on reddit](https://new.reddit.com/r/OLED_Gaming/comments/sbords/comment/lin39um/) - where someone on Win10 said it wouldn't work unless he installed v8.0.0 (none of the newer ones).

I have Win11 23H2 and only need x64 versions of the Desktop Runtime and the ASP.NET Core.

**Comment by nommy125** [comment]
followed #393, i installed both ASP.NET Core 8.0.7 and Desktop Runtime 8.0.7 (tried 8.0.8 too) and still seeing the same message, I'm on windows 11 22631.4037

**Comment by nommy125** [comment]
update: Updating to latest version (10.0.1.0) and updating Desktop and ASP.NET to 8.0.8 fixed the issue
