### ISSUE TITLE
EnergySaving(screen_off) on C1

### ISSUE THREAD

**Issue by lowfat32** [Maassoft/ColorControl#47]
Have a C9 and a C1. On the C9 I am able to use App:HDMI1, and Step: EnergySaving(screen_off) to turn the display off (but tv stays on). But it doesn't work on the C1.  No error in log. 

I am able to use another app to turn off the display with "com.webos.service.tvpower/power/turnOffScreen"
https://github.com/bendavid/aiopylgtv      

So is another way to turn off the display? Or would it be possible to add the tvpower 'app'?

Thanks.

**Comment by Maassoft** [comment]
ColorControl uses "ssap://system/turnOff", maybe it's not supported (anymore) by the C1 due to newer WebOS?
But is there any functionality that does work with your C1? If not, then maybe the initial handshake did not complete successfully. Upon initial startup, was there a popup on the C1 to allow control of the tv by the app?
You can force this again by deleting the <ip-address>_ClientKey.txt file in the settings folder:
C:\Users\username\AppData\Roaming\Maassoft\ColorControl

You could also try if the power button works by clicking on it on the remote control image or creating a preset with the step Buttons->POWER.

**Comment by lowfat32** [comment]
The other shortcuts are working, using Backlight(#) to adjust oled light and it works perfect.  Most things on remote work. But the power button on the remote in the app also doesn't do anything.

**Comment by Maassoft** [comment]
Ah, you're talking specifically about turning off the screen, but not the entire tv. I will test if I can get this working on my C9 with that particular command (turnOffScreen) and if it works it will be added to the next release.

**Comment by Maassoft** [comment]
I've just released 4.3.0.0 which has the new actions "turnScreenOff" and "turnScreenOn". Please test if it works on your C1.

**Comment by lowfat32** [comment]
Awesome it works great. Thanks for adding it so quickly!
