### ISSUE TITLE
Suggestion: per-process mode presets or automatic game detection

### ISSUE THREAD

**Issue by Joshaze** [Maassoft/ColorControl#87]
I'd love to be able to have ColorControl apply a mode preset based on what application I'm in.

For example, for a game that uses HDR and where I need a 10+bpc I have to lower my resolution to 1080p due to my GPUs limited HDMI 2.1 support. I would love to be able to assign a "mode preset" to a specific process that would enable HDR and set the optimal color format, dynamic range, resolution, and refresh rate when that process was launched.

I'd also like to have HDR mode disabled unless I'm playing a game and HDR should only be enabled for some games so maybe a default mode preset could be enforced unless another preset or process overrides it and there could be options in CC or even per-mode preset triggers that could be customized.

I realize this may be impossible or might otherwise conflict with games that detect HDR mode upon launch as ColorControl would have to apply the mode change before the app launches... Perhaps there is a way to have it monitor app launches, check if it matches a mode preset, set the mode preset, and then proceeds with launching the app?

If this would not be possible could CC be made game-aware so that it stores the current mode settings and upon exiting a game, it restores those settings? (Some games enable HDR mode upon game launch but don't turn it back off afterward)

**Comment by Maassoft** [comment]
You can already automatically start a Nvidia preset upon launching a game by including it in the steps of a LG preset. But changing HDR is finicky because the game is already starting and HDR is activated too late in must occurrences. Currently I have no means to "block" the loading of a game. My app would need admin/system rights then and probably needs to run as a service or even as a driver to be able to intervene in starting of processes.

Currently the easiest way would be starting the games from ColorControl itself, but then there is already an app for that:
https://github.com/Codectory/AutoActions
Maybe you could try out that app for these specific usages?
