### ISSUE TITLE
ColorControl won't launch on PC startup and once manually launched won't turn on the TV via WiFi

### ISSUE THREAD

**Issue by clotobee** [Maassoft/ColorControl#89]
LG C1 OLED is connected at the same router (Honor Router 3) as the PC. TV is connected via WiFi and PC via LAN. TV can get detected by ColorControl and I can set all the settings. Also on the TV I turned on the remote control via WiFi. I want ColorControl to run on startup and turn on the TV on startup so I set Options > Automatically start after login: On and all automatic TV controls On (power on on startup included). Both ColorControl and TV won't launch on startup and I need to manually launch CC and manually turn on TV. What am I missing? 

I got three monitor setup: 
monitor 1- CRG9 ultrawide
monitor 2- PG279Q
monitor 3- LG C1

Also whenever I start windows I get this bug that if TV is not turned on, my graphics card (3080 ti) only detects one monitor (monitor 1). I need to manually turn on TV to make all monitors available. 

Thanks in advance

**Comment by Maassoft** [comment]
Maybe the scheduled task hasn't been created correctly. Can you look at the "Task Scheduler" and see if there is a task named "ColorControl", see this screenshot:
![image](https://user-images.githubusercontent.com/70057942/160235475-77800083-47a3-430c-b76c-e0bbe7bf56b1.png)

Currently I'm testing if activating the LG service of ColorControl before the Nvidia service improves turning on the TV after PC startup. The Nvidia service is now activated before the LG service and seems to block initializing the Nvidia API (sometimes) if the TV is not turned on. I'm not 100% sure yet, but at least that's what it looks like. Hopefully this will then be fixed in the next version.

**Comment by clotobee** [comment]
Thanks for the reply!

Yeah, the scheduled task is there. I tweaked some settings there to make it run "with maximum privileges" and "configured for Windows 10". Also I set to repeat the task 3 times if error occurs. Hope in this way it will work. It is a real bother with this setup to have to manually turn on every monitor to make just one monitor run properly. 

Thanks for your job. Keep it up!

**Comment by clotobee** [comment]
Sorry man, I'm an idiot. Just figured out I set the scheduled task and then moved the folder to another path. That should now work fine. Thanks again

**Comment by clotobee** [comment]
> Maybe the scheduled task hasn't been created correctly. Can you look at the "Task Scheduler" and see if there is a task named "ColorControl", see this screenshot: ![image](https://user-images.githubusercontent.com/70057942/160235475-77800083-47a3-430c-b76c-e0bbe7bf56b1.png)
> 
> Currently I'm testing if activating the LG service of ColorControl before the Nvidia service improves turning on the TV after PC startup. The Nvidia service is now activated before the LG service and seems to block initializing the Nvidia API (sometimes) if the TV is not turned on. I'm not 100% sure yet, but at least that's what it looks like. Hopefully this will then be fixed in the next version.

Hi man, I just downloaded the new version 5.6 and now TV turns on like a charm! Thanks a lot. Only thing is everytime I startup my PC I now get this waraning:

https://imgur.com/a/xg5XDam

I can share the log text if needed. Thanks
